### ISSUE TITLE
现在是2020年12月，这个工具似乎抓取不到搜索结果了

### ISSUE THREAD

**Issue by fox1383164k** [shadoweb/baidukeywords#1]
现在是2020年12月，这个工具似乎抓取不到搜索结果了
，我试了几个词，显示结果都是0

**Comment by shadoweb** [comment]
$preg='/<div\s+class=\"f13[\s\S]*?\"><a\s+target=\"_blank\"\s+href=\"[^>]+\">[\s\S]*?<\/a><\/div>/i';
f13这里添加一下[\s\S]*?就行了.
百度更新了页面的html

**Comment by shadoweb** [comment]
另外,这个要看你的服务器配置,只是学习用的,
实际上个人使用简单了解一下还行.
如果真靠这个检测,还有很多要优化的地方.

**Comment by shadoweb** [comment]
更了.
